[package]
name = "notoriety-cli"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Encrypted note-taking application with cloud sharing"
homepage = "https://github.com/dmgolembiowski/notoriety"
repository = "https://github.com/dmgolembiowski/notoriety"
readme = "README.md"
categories = ["command-line-utilities", "development-tools", "text-editors", "network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
